import sys
import os
from dotenv import load_dotenv
from langchain_core.chat_history import BaseChatMessageHistory
from langchain_community.chat_message_histories import ChatMessageHistory,InMemoryChatMessageHistory
from langchain_community.vectorstores import FAISS
from langchain_core.runnables import RunnableWithMessageHistory
from langchain.chains import create_history_aware_retreiver,create_retreival_chain
from langchain.chains.combine_documents import create_stuff_documents_chain
from utils.model_loader import ModelLoader
from exception.custom_exception import DocumentPortalException
from logger.custom_logger import CustomLogger
from promptengg.promptlibrary import PROMPT_REGISTRY
from model.models import *

class ConversationalRAG:
    def __init__(self,session_id:str, retriever):
        try:
            load_dotenv()
            self.log = CustomLogger().get_logger(__name__)
            self.session_id = session_id
            self.retriever = retriever
            self.loader = ModelLoader()
            self.llm = self.loader.load_llm()
            self.contexualize_prompt=PROMPT_REGISTRY[PromptType.CONTEXTUALIZE_QUESTION.value]
            self.qa_prompt=PROMPT_REGISTRY[PromptType.CONTEXT_QA.value]
            self.history_aware_retriever=create_history_aware_retreiver(
                self.llm,self.retriever,self.contexualize_prompt)
                    
            self.log.info("Created history aware retriever", session_id=session_id)
            self.qa_chain=create_stuff_documents_chain(self.llm,self.qa_prompt)
            self.rag_chain=create_retreival_chain(self.history_aware_retriever,self.qa_chain)

            self.log.info("Initialized and created RAG chain", session_id=session_id)

            self.chain = RunnableWithMessageHistory(
                self.rag_chain, 
                self._get_session_history,
                input_message_key="input",
                history_message_keys="chat_history",
                output_message_key="answer"

            )


            self.log.info("Runnablewithmessage history created.", session_id=self.session_id)

        except Exception as e:
            self.log.error(f"Error initializing ConversationalRAG: {e}")
    def _load_llm(self):
        try:
            llm=ModelLoader().load_llm()
            self.log.info("LLM loaded here", class_name=llm.__class__.__name__)
            return llm
        except Exception as e:
            self.log.error(f"Error loading LLM: {e}")
            raise DocumentPortalException(e)


    def _get_session_history(self):
        try:
            pass    

        except Exception as e:
            self.log.error(f"Error getting session history: {e}")
            raise DocumentPortalException(e)    
        
    def load_retriever_from_faiss(self, index_path:str):
        try:
            embeddings= ModelLoader().load_embeddings()
            if not os.path.isdir(index_path):
                raise DocumentPortalException(f"FAISS index directory not found at {index_path}")
            vector_store= FAISS.load_local(index_path, embeddings)
            self.log.info("FAISS retriever loaded successfully.", index_path=index_path, session_id=self.session_id)
            return vector_store.as_retriever(search_type="similarity", search_kwargs={"k": 5})

        except Exception as e:
            self.log.error(f"Error loading retriever from FAISS: {e}")
            raise DocumentPortalException(e)    
        
    def invoke(self,user_input:str) -> str:
        try:
            response= self.chain.invoke(
                {"input": user_input},
                config={"configurable":{"session_id": self.session_id}}
            )
            answer= response.get("answer","No answer")
            if not answer:
                self.log.warning("No answer generated by the RAG chain.", session_id=self.session_id)
            self.log.info("RAG Chain invoked successfully", session_id=self.session_id,user_input=user_input, answer=answer)
            return answer
        except Exception as e:
            self.log.error(f"Error invoking ConversationalRAG: {e}")
            raise DocumentPortalException(e)    